-- 1.- CREAR TABLA CLIENTES
DROP TABLE CLIENTES;
CREATE TABLE CLIENTES (
	ID NUMBER PRIMARY KEY,
	NOMBRES VARCHAR2(200),
	APELLIDOS VARCHAR2(200),
	EMAIL VARCHAR2(100),
	DIRECCION VARCHAR2(500),
	FECHA_CREACION TIMESTAMP
);

-- 2.- CREAR TABLA PRODUCTOS
CREATE TABLE PRODUCTOS (
	ID NUMBER PRIMARY KEY,
	DESCRIPCION VARCHAR2(200),
	PRECIO_UNITARIO NUMBER,
	STOCK NUMBER,
	ESTADO VARCHAR2(20),
	FECHA_CREACION TIMESTAMP
);

-- 3.- CREAR TABLA PEDIDOS
CREATE TABLE PEDIDOS (
	ID NUMBER PRIMARY KEY,
	CLIENTE_ID NUMBER,
	FECHA DATE,
	ESTADO VARCHAR2(20),
	TOTAL NUMBER,
	FECHA_CREACION TIMESTAMP,
	CONSTRAINT FK_PEDIDOS_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(ID)
);

-- 4.- CREAR TABLE DETALLES PEDIDOS
CREATE TABLE PEDIDO_DETALLES (
	ID NUMBER PRIMARY KEY,
	PEDIDO_ID NUMBER,
	PRODUCTO_ID NUMBER,
	CANTIDAD NUMBER,
	SUBTOTAL NUMBER,
	FECHA_CREACION TIMESTAMP,
	CONSTRAINT FK_DETALLES_PEDIDO FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDOS(ID),
	CONSTRAINT FK_DETALLES_PRODUCTO FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS(ID)
);

-- 5.- CREAR SECUENCIAS PARA TABLAS
CREATE SEQUENCE CLIENTES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE PRODUCTOS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE PEDIDOS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE DETALLE_PEDIDOS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 6.- INSERTAR DATA
INSERT INTO CLIENTES (ID, NOMBRES, APELLIDOS, EMAIL, DIRECCION, FECHA_CREACION) VALUES (CLIENTES_SEQ.NEXTVAL, 'Carlos', 'Pérez', 'carlos.perez@example.com', 'Av. Siempre Viva 123, Lima, Perú', SYSTIMESTAMP);
INSERT INTO CLIENTES (ID, NOMBRES, APELLIDOS, EMAIL, DIRECCION, FECHA_CREACION) VALUES (CLIENTES_SEQ.NEXTVAL, 'María', 'Gómez', 'maria.gomez@example.com', 'Calle 45 No. 12-34, Bogotá, Colombia', SYSTIMESTAMP);
INSERT INTO CLIENTES (ID, NOMBRES, APELLIDOS, EMAIL, DIRECCION, FECHA_CREACION) VALUES (CLIENTES_SEQ.NEXTVAL, 'Juan', 'Rodríguez', 'juan.rod@example.com', 'Calle Falsa 456, Quito, Ecuador', SYSTIMESTAMP);
INSERT INTO CLIENTES (ID, NOMBRES, APELLIDOS, EMAIL, DIRECCION, FECHA_CREACION) VALUES (CLIENTES_SEQ.NEXTVAL, 'Lucía', 'Fernández', 'lucia.fernandez@example.com', 'Av. Independencia 99, Caracas, Venezuela', SYSTIMESTAMP);
INSERT INTO CLIENTES (ID, NOMBRES, APELLIDOS, EMAIL, DIRECCION, FECHA_CREACION) VALUES (CLIENTES_SEQ.NEXTVAL, 'Pedro', 'Martínez', 'pedro.martinez@example.com', 'Calle San Martín 77, Santiago, Chile', SYSTIMESTAMP);
INSERT INTO CLIENTES (ID, NOMBRES, APELLIDOS, EMAIL, DIRECCION, FECHA_CREACION) VALUES (CLIENTES_SEQ.NEXTVAL, 'Ana', 'Torres', 'ana.torres@example.com', 'Calle Libertad 22, Buenos Aires, Argentina', SYSTIMESTAMP);
INSERT INTO CLIENTES (ID, NOMBRES, APELLIDOS, EMAIL, DIRECCION, FECHA_CREACION) VALUES (CLIENTES_SEQ.NEXTVAL, 'Luis', 'Ramírez', 'luis.ramirez@example.com', 'Cra. 7 #45-60, Medellín, Colombia', SYSTIMESTAMP);
INSERT INTO CLIENTES (ID, NOMBRES, APELLIDOS, EMAIL, DIRECCION, FECHA_CREACION) VALUES (CLIENTES_SEQ.NEXTVAL, 'Carmen', 'Ruiz', 'carmen.ruiz@example.com', 'Rua das Flores 100, São Paulo, Brasil', SYSTIMESTAMP);
INSERT INTO CLIENTES (ID, NOMBRES, APELLIDOS, EMAIL, DIRECCION, FECHA_CREACION) VALUES (CLIENTES_SEQ.NEXTVAL, 'Miguel', 'Sánchez', 'miguel.sanchez@example.com', 'Av. Reforma 1500, Ciudad de México, México', SYSTIMESTAMP);
INSERT INTO CLIENTES (ID, NOMBRES, APELLIDOS, EMAIL, DIRECCION, FECHA_CREACION) VALUES (CLIENTES_SEQ.NEXTVAL, 'Paula', 'Castro', 'paula.castro@example.com', 'Calle Palma 123, La Paz, Bolivia', SYSTIMESTAMP);
INSERT INTO CLIENTES (ID, NOMBRES, APELLIDOS, EMAIL, DIRECCION, FECHA_CREACION) VALUES (CLIENTES_SEQ.NEXTVAL, 'Diego', 'Morales', 'diego.morales@example.com', 'Av. del Sol 88, Asunción, Paraguay', SYSTIMESTAMP);
INSERT INTO CLIENTES (ID, NOMBRES, APELLIDOS, EMAIL, DIRECCION, FECHA_CREACION) VALUES (CLIENTES_SEQ.NEXTVAL, 'Valentina', 'Rojas', 'valentina.rojas@example.com', 'Calle Los Olivos 56, Montevideo, Uruguay', SYSTIMESTAMP);
INSERT INTO CLIENTES (ID, NOMBRES, APELLIDOS, EMAIL, DIRECCION, FECHA_CREACION) VALUES (CLIENTES_SEQ.NEXTVAL, 'Andrés', 'Mendoza', 'andres.mendoza@example.com', 'Av. Marítima 120, Guayaquil, Ecuador', SYSTIMESTAMP);
INSERT INTO CLIENTES (ID, NOMBRES, APELLIDOS, EMAIL, DIRECCION, FECHA_CREACION) VALUES (CLIENTES_SEQ.NEXTVAL, 'Daniela', 'Jiménez', 'daniela.jimenez@example.com', 'Calle Mayor 99, Madrid, España', SYSTIMESTAMP);
INSERT INTO CLIENTES (ID, NOMBRES, APELLIDOS, EMAIL, DIRECCION, FECHA_CREACION) VALUES (CLIENTES_SEQ.NEXTVAL, 'Sofía', 'Vargas', 'sofia.vargas@example.com', 'Rua Central 200, Lisboa, Portugal', SYSTIMESTAMP);
INSERT INTO CLIENTES (ID, NOMBRES, APELLIDOS, EMAIL, DIRECCION, FECHA_CREACION) VALUES (CLIENTES_SEQ.NEXTVAL, 'Jorge', 'Navarro', 'jorge.navarro@example.com', 'Callejón del Beso 10, Guanajuato, México', SYSTIMESTAMP);
INSERT INTO CLIENTES (ID, NOMBRES, APELLIDOS, EMAIL, DIRECCION, FECHA_CREACION) VALUES (CLIENTES_SEQ.NEXTVAL, 'Patricia', 'Herrera', 'patricia.herrera@example.com', 'Av. de los Incas 102, Cusco, Perú', SYSTIMESTAMP);
INSERT INTO CLIENTES (ID, NOMBRES, APELLIDOS, EMAIL, DIRECCION, FECHA_CREACION) VALUES (CLIENTES_SEQ.NEXTVAL, 'Alejandro', 'Silva', 'alejandro.silva@example.com', 'Camino Real 77, Tegucigalpa, Honduras', SYSTIMESTAMP);
INSERT INTO CLIENTES (ID, NOMBRES, APELLIDOS, EMAIL, DIRECCION, FECHA_CREACION) VALUES (CLIENTES_SEQ.NEXTVAL, 'Renata', 'Ortega', 'renata.ortega@example.com', 'Calle 8 #33-22, Cali, Colombia', SYSTIMESTAMP);
INSERT INTO CLIENTES (ID, NOMBRES, APELLIDOS, EMAIL, DIRECCION, FECHA_CREACION) VALUES (CLIENTES_SEQ.NEXTVAL, 'Sebastián', 'Reyes', 'sebastian.reyes@example.com', 'Pasaje Central 34, Managua, Nicaragua', SYSTIMESTAMP);
INSERT INTO CLIENTES (ID, NOMBRES, APELLIDOS, EMAIL, DIRECCION, FECHA_CREACION) VALUES (CLIENTES_SEQ.NEXTVAL, 'Julieta', 'Delgado', 'julieta.delgado@example.com', 'Calle Nueva 89, San Salvador, El Salvador', SYSTIMESTAMP);
INSERT INTO CLIENTES (ID, NOMBRES, APELLIDOS, EMAIL, DIRECCION, FECHA_CREACION) VALUES (CLIENTES_SEQ.NEXTVAL, 'Gabriel', 'Acuña', 'gabriel.acuna@example.com', 'Carrera Central 101, Barranquilla, Colombia', SYSTIMESTAMP);
INSERT INTO CLIENTES (ID, NOMBRES, APELLIDOS, EMAIL, DIRECCION, FECHA_CREACION) VALUES (CLIENTES_SEQ.NEXTVAL, 'Martina', 'López', 'martina.lopez@example.com', 'Av. Atlántico 77, Puerto La Cruz, Venezuela', SYSTIMESTAMP);
INSERT INTO CLIENTES (ID, NOMBRES, APELLIDOS, EMAIL, DIRECCION, FECHA_CREACION) VALUES (CLIENTES_SEQ.NEXTVAL, 'Tomás', 'Ibarra', 'tomas.ibarra@example.com', 'Calle Central 33, Santa Cruz, Bolivia', SYSTIMESTAMP);
INSERT INTO CLIENTES (ID, NOMBRES, APELLIDOS, EMAIL, DIRECCION, FECHA_CREACION) VALUES (CLIENTES_SEQ.NEXTVAL, 'Nicole', 'Figueroa', 'nicole.figueroa@example.com', 'Av. del Este 11, Maracaibo, Venezuela', SYSTIMESTAMP);
INSERT INTO CLIENTES (ID, NOMBRES, APELLIDOS, EMAIL, DIRECCION, FECHA_CREACION) VALUES (CLIENTES_SEQ.NEXTVAL, 'Iván', 'Carrillo', 'ivan.carrillo@example.com', 'Rua Nova 56, Porto Alegre, Brasil', SYSTIMESTAMP);
INSERT INTO CLIENTES (ID, NOMBRES, APELLIDOS, EMAIL, DIRECCION, FECHA_CREACION) VALUES (CLIENTES_SEQ.NEXTVAL, 'Isabel', 'Campos', 'isabel.campos@example.com', 'Calle Real 45, Panamá, Panamá', SYSTIMESTAMP);
INSERT INTO CLIENTES (ID, NOMBRES, APELLIDOS, EMAIL, DIRECCION, FECHA_CREACION) VALUES (CLIENTES_SEQ.NEXTVAL, 'Fernando', 'Cordero', 'fernando.cordero@example.com', 'Av. Kennedy 80, Santiago, Chile', SYSTIMESTAMP);

-- INSERT PRODUCTO
INSERT INTO PRODUCTOS (ID, DESCRIPCION, PRECIO_UNITARIO, STOCK, ESTADO, FECHA_CREACION) VALUES (PRODUCTOS_SEQ.NEXTVAL, 'Laptop Dell Inspiron 15', '899.99', 50, 'ACTIVO', SYSTIMESTAMP);
INSERT INTO PRODUCTOS (ID, DESCRIPCION, PRECIO_UNITARIO, STOCK, ESTADO, FECHA_CREACION) VALUES (PRODUCTOS_SEQ.NEXTVAL, 'Smartphone Samsung Galaxy S23', '799.00', 100, 'ACTIVO', SYSTIMESTAMP);
INSERT INTO PRODUCTOS (ID, DESCRIPCION, PRECIO_UNITARIO, STOCK, ESTADO, FECHA_CREACION) VALUES (PRODUCTOS_SEQ.NEXTVAL, 'Teclado Mecánico Logitech G413', '99.90', 30, 'ACTIVO', SYSTIMESTAMP);
INSERT INTO PRODUCTOS (ID, DESCRIPCION, PRECIO_UNITARIO, STOCK, ESTADO, FECHA_CREACION) VALUES (PRODUCTOS_SEQ.NEXTVAL, 'Mouse Inalámbrico Logitech M185', '25.50', 75, 'ACTIVO', SYSTIMESTAMP);
INSERT INTO PRODUCTOS (ID, DESCRIPCION, PRECIO_UNITARIO, STOCK, ESTADO, FECHA_CREACION) VALUES (PRODUCTOS_SEQ.NEXTVAL, 'Monitor LG 24 pulgadas', '180.00', 20, 'ACTIVO', SYSTIMESTAMP);
INSERT INTO PRODUCTOS (ID, DESCRIPCION, PRECIO_UNITARIO, STOCK, ESTADO, FECHA_CREACION) VALUES (PRODUCTOS_SEQ.NEXTVAL, 'Impresora HP DeskJet 2710', '110.30', 15, 'ACTIVO', SYSTIMESTAMP);
INSERT INTO PRODUCTOS (ID, DESCRIPCION, PRECIO_UNITARIO, STOCK, ESTADO, FECHA_CREACION) VALUES (PRODUCTOS_SEQ.NEXTVAL, 'Disco Duro Externo 1TB Seagate', '69.99', 40, 'ACTIVO', SYSTIMESTAMP);
INSERT INTO PRODUCTOS (ID, DESCRIPCION, PRECIO_UNITARIO, STOCK, ESTADO, FECHA_CREACION) VALUES (PRODUCTOS_SEQ.NEXTVAL, 'Memoria USB 64GB Kingston', '14.50', 120, 'ACTIVO', SYSTIMESTAMP);
INSERT INTO PRODUCTOS (ID, DESCRIPCION, PRECIO_UNITARIO, STOCK, ESTADO, FECHA_CREACION) VALUES (PRODUCTOS_SEQ.NEXTVAL, 'Tablet Lenovo M10', '230.00', 35, 'ACTIVO', SYSTIMESTAMP);
INSERT INTO PRODUCTOS (ID, DESCRIPCION, PRECIO_UNITARIO, STOCK, ESTADO, FECHA_CREACION) VALUES (PRODUCTOS_SEQ.NEXTVAL, 'Silla Gamer Cougar Armor One', '210.99', 10, 'ACTIVO', SYSTIMESTAMP);
INSERT INTO PRODUCTOS (ID, DESCRIPCION, PRECIO_UNITARIO, STOCK, ESTADO, FECHA_CREACION) VALUES (PRODUCTOS_SEQ.NEXTVAL, 'Webcam Logitech C920', '85.00', 25, 'ACTIVO', SYSTIMESTAMP);
INSERT INTO PRODUCTOS (ID, DESCRIPCION, PRECIO_UNITARIO, STOCK, ESTADO, FECHA_CREACION) VALUES (PRODUCTOS_SEQ.NEXTVAL, 'Micrófono Blue Yeti', '129.90', 18, 'ACTIVO', SYSTIMESTAMP);
INSERT INTO PRODUCTOS (ID, DESCRIPCION, PRECIO_UNITARIO, STOCK, ESTADO, FECHA_CREACION) VALUES (PRODUCTOS_SEQ.NEXTVAL, 'Audífonos Sony WH-1000XM4', '299.99', 22, 'ACTIVO', SYSTIMESTAMP);
INSERT INTO PRODUCTOS (ID, DESCRIPCION, PRECIO_UNITARIO, STOCK, ESTADO, FECHA_CREACION) VALUES (PRODUCTOS_SEQ.NEXTVAL, 'Router TP-Link AC1350', '55.80', 60, 'ACTIVO', SYSTIMESTAMP);
INSERT INTO PRODUCTOS (ID, DESCRIPCION, PRECIO_UNITARIO, STOCK, ESTADO, FECHA_CREACION) VALUES (PRODUCTOS_SEQ.NEXTVAL, 'Cámara de Seguridad Ezviz', '89.90', 27, 'ACTIVO', SYSTIMESTAMP);
INSERT INTO PRODUCTOS (ID, DESCRIPCION, PRECIO_UNITARIO, STOCK, ESTADO, FECHA_CREACION) VALUES (PRODUCTOS_SEQ.NEXTVAL, 'Smartwatch Amazfit GTS 4', '120.00', 45, 'ACTIVO', SYSTIMESTAMP);
INSERT INTO PRODUCTOS (ID, DESCRIPCION, PRECIO_UNITARIO, STOCK, ESTADO, FECHA_CREACION) VALUES (PRODUCTOS_SEQ.NEXTVAL, 'Cable HDMI 2m', '9.99', 200, 'ACTIVO', SYSTIMESTAMP);
INSERT INTO PRODUCTOS (ID, DESCRIPCION, PRECIO_UNITARIO, STOCK, ESTADO, FECHA_CREACION) VALUES (PRODUCTOS_SEQ.NEXTVAL, 'Base para Laptop con Ventilador', '34.00', 55, 'ACTIVO', SYSTIMESTAMP);
INSERT INTO PRODUCTOS (ID, DESCRIPCION, PRECIO_UNITARIO, STOCK, ESTADO, FECHA_CREACION) VALUES (PRODUCTOS_SEQ.NEXTVAL, 'Cargador USB-C Samsung', '18.50', 90, 'ACTIVO', SYSTIMESTAMP);
INSERT INTO PRODUCTOS (ID, DESCRIPCION, PRECIO_UNITARIO, STOCK, ESTADO, FECHA_CREACION) VALUES (PRODUCTOS_SEQ.NEXTVAL, 'Hub USB 4 Puertos', '22.75', 80, 'ACTIVO', SYSTIMESTAMP);
INSERT INTO PRODUCTOS (ID, DESCRIPCION, PRECIO_UNITARIO, STOCK, ESTADO, FECHA_CREACION) VALUES (PRODUCTOS_SEQ.NEXTVAL, 'Smart TV LG 50"', '499.00', 12, 'ACTIVO', SYSTIMESTAMP);
INSERT INTO PRODUCTOS (ID, DESCRIPCION, PRECIO_UNITARIO, STOCK, ESTADO, FECHA_CREACION) VALUES (PRODUCTOS_SEQ.NEXTVAL, 'Reproductor Blu-Ray Sony', '89.90', 14, 'INACTIVO', SYSTIMESTAMP);
INSERT INTO PRODUCTOS (ID, DESCRIPCION, PRECIO_UNITARIO, STOCK, ESTADO, FECHA_CREACION) VALUES (PRODUCTOS_SEQ.NEXTVAL, 'Control Xbox Series X', '64.99', 33, 'ACTIVO', SYSTIMESTAMP);
INSERT INTO PRODUCTOS (ID, DESCRIPCION, PRECIO_UNITARIO, STOCK, ESTADO, FECHA_CREACION) VALUES (PRODUCTOS_SEQ.NEXTVAL, 'Joystick Logitech F310', '29.00', 48, 'ACTIVO', SYSTIMESTAMP);
INSERT INTO PRODUCTOS (ID, DESCRIPCION, PRECIO_UNITARIO, STOCK, ESTADO, FECHA_CREACION) VALUES (PRODUCTOS_SEQ.NEXTVAL, 'Tarjeta de Memoria SD 128GB', '22.90', 150, 'ACTIVO', SYSTIMESTAMP);
INSERT INTO PRODUCTOS (ID, DESCRIPCION, PRECIO_UNITARIO, STOCK, ESTADO, FECHA_CREACION) VALUES (PRODUCTOS_SEQ.NEXTVAL, 'Proyector Epson X41', '379.00', 6, 'ACTIVO', SYSTIMESTAMP);
INSERT INTO PRODUCTOS (ID, DESCRIPCION, PRECIO_UNITARIO, STOCK, ESTADO, FECHA_CREACION) VALUES (PRODUCTOS_SEQ.NEXTVAL, 'Sistema de sonido Sony 2.1', '180.00', 9, 'ACTIVO', SYSTIMESTAMP);
INSERT INTO PRODUCTOS (ID, DESCRIPCION, PRECIO_UNITARIO, STOCK, ESTADO, FECHA_CREACION) VALUES (PRODUCTOS_SEQ.NEXTVAL, 'UPS APC 1000VA', '145.50', 13, 'ACTIVO', SYSTIMESTAMP);
INSERT INTO PRODUCTOS (ID, DESCRIPCION, PRECIO_UNITARIO, STOCK, ESTADO, FECHA_CREACION) VALUES (PRODUCTOS_SEQ.NEXTVAL, 'Repetidor WiFi Xiaomi', '19.90', 66, 'ACTIVO', SYSTIMESTAMP);
INSERT INTO PRODUCTOS (ID, DESCRIPCION, PRECIO_UNITARIO, STOCK, ESTADO, FECHA_CREACION) VALUES (PRODUCTOS_SEQ.NEXTVAL, 'Cámara DSLR Canon EOS 250D', '599.99', 7, 'ACTIVO', SYSTIMESTAMP);

-- CREAR PROCEDURE:
CREATE OR REPLACE PROCEDURE SP_GET_PRODUCTOS(
    RESULTADO OUT SYS_REFCURSOR
)
IS
BEGIN
    OPEN RESULTADO FOR
    SELECT ID, DESCRIPCION, PRECIO_UNITARIO, STOCK, ESTADO, FECHA_CREACION
    FROM PRODUCTOS
    ORDER BY DESCRIPCION;
END;